routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('frontend.index');
// });

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/collections', 'HomeController@getCollections')->name('collections');
Route::get('/products', 'HomeController@getCollections');
Route::get('/search', 'HomeController@getSearchProducts')->name('product_search');
Route::get('/collections/{slug}', 'HomeController@getCollectionProducts')->name('collection_products');
Route::get('/products/{slug}', 'HomeController@getProductDetail')->name('product_details');
Route::get('/collections/pages/{slug}', 'HomeController@getPagesDetail')->name('pages_details');
Route::post('/products/add-to-cart', 'HomeController@addToCart')->name('add_to_cart');
Route::get('cart', 'HomeController@myShoppingCart')->name('my_cart');
Route::post('remove-from-cart', 'HomeController@removeFromCart');
Route::post('update-cart', 'HomeController@updateCart');
Route::get('checkout', 'HomeController@cartCheckout')->name('checkout');


Route::group(['as'=>'admin.','prefix' => 'admin','namespace'=>'Admin','middleware'=>['auth','admin']], function () {
		Route::get('dashboard', 'DashboardController@index')->name('dashboard');
		Route::get('products/add', 'DashboardController@addProduct')->name('add_product');
		Route::post('products/add', 'DashboardController@addProductPost')->name('add_product_post');
		Route::get('products', 'DashboardController@allProducts')->name('products');
		Route::get('products/{id}', 'DashboardController@getProductDetails')->name('product_details');
		Route::get('products/{id}/edit', 'DashboardController@getProductEdit')->name('product_edit');
		Route::post('products/{id}/edit', 'DashboardController@productUpdate')->name('product_update');
		Route::get('products/{id}/delete', 'DashboardController@deletProduct')->name('product_delete');
		Route::get('categories', 'DashboardController@allCategories')->name('categories');
		Route::get('category/{id}/products', 'DashboardController@getCategoryProducts')->name('category_products');

		Route::get('category/{id}/delete', 'DashboardController@deleteCategory')->name('category_delete');
		Route::get('category/add', 'DashboardController@addCategory')->name('add_category');
		Route::post('category/add', 'DashboardController@addCategoryPost')->name('add_category_post');

		Route::get('category/{id}/edit', 'DashboardController@getCategoryEdit')->name('category_edit');
		Route::post('category/{id}/edit', 'DashboardController@categoryUpdate')->name('category_update');

		Route::get('all-pages', 'DashboardController@productDocumentationPages')->name('all_pages');
		Route::get('add-new-page', 'DashboardController@addNewPage')->name('add_new_page');
		Route::post('add-new-page', 'DashboardController@addNewPagePost')->name('new_page_post');

		Route::get('page/{id}', 'DashboardController@getPageEdit')->name('page_edit');
		Route::post('page/{id}', 'DashboardController@pageUpdatePost')->name('page_update');
		Route::get('page/{id}/delete', 'DashboardController@deletePage')->name('page_delete');



});

Route::group(['as'=>'user.','prefix' => 'user','namespace'=>'User','middleware'=>['auth','user']], function () {
		Route::get('my-account', 'DashboardController@myAccount')->name('my_account');
		Route::post('my-account', 'DashboardController@updateUserPost')->name('update_account');
		Route::get('change-password', 'DashboardController@changePassword')->name('change_password');
		Route::post('change-password', 'DashboardController@changePasswordPost')->name('update_password');

		Route::post('pay-now', 'PayPalController@makepayment')->name('make_payment');
		Route::get('payment/success', 'PayPalController@success')->name('payment.success');
		Route::get('payment/cancel', 'PayPalController@cancel')->name('payment.cancel');

		Route::get('transactions', 'PayPalController@transactionHistory')->name('transaction_history');
		Route::get('transactions/{id}', 'PayPalController@transactionDetails')->name('transaction_detail');
});


Route::group(['as'=>'pages.','prefix' => 'pages'], function () {
		Route::get('news', 'PagesController@news')->name('news');
		Route::get('product-documentation', 'PagesController@productDocumentation')->name('product_documentation');
		Route::get('contact-us', 'PagesController@contactUs')->name('contact_us');
		Route::post('contact-us', 'PagesController@contactPost')->name('contact_post');
		Route::get('terms-conditions', 'PagesController@termsAndConditions')->name('terms_conditions');
		Route::get('faq', 'PagesController@faq')->name('faq');
		
		Route::get('about-us', 'PagesController@aboutUs')->name('about_us');
});

resources/views/admin/add-category.blade.php
@extends('layouts.admin-app')

@section('content')
<div class="xs-pd-20-10">
  <div class="min-height-200px mb-30">
    <div class="page-header">
      <div class="row">
        <div class="col-md-6 col-sm-12">
          <div class="title">
            <h4>Category</h4>
          </div>
          <nav aria-label="breadcrumb" role="navigation">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{{route('admin.categories')}}">Category</a></li>
              <li class="breadcrumb-item active" aria-current="page">Add Category</li>
            </ol>
          </nav>
        </div>
        <div class="col-md-6 col-sm-12 text-right">
          <a class="btn btn-primary" href="{{route('admin.categories')}}" role="button">Back
          </a>
        </div>
      </div>
    </div>

    <!-- Select-2 Start -->
    <div class="pd-20 card-box mb-30">
      <div class="clearfix">
        <div class="pull-left">
          <h4 class="text-blue h4">Add New Category</h4>
          
        </div>
      </div>
      @if(session('error')) 
           <div class="alert alert-danger mb-4" role="alert"> <i class="flaticon-cancel-12 close" data-dismiss="alert"></i>{!! session('error') !!}</div>
            
           @endif
           @if(session('success')) 
           <div class="alert alert-success mb-4" role="alert"> 
            <i class="flaticon-cancel-12 close" data-dismiss="alert"></i>{!! session('success') !!}</div>
            
         @endif
      <form class="row" action="{{route('admin.add_category_post')}}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-group col-md-12">
          <label>*Category Name</label>
          <input class="form-control" name="category_name" value="{{old('category_name')}}" type="text" placeholder="category name">
          @if ($errors->has('category_name'))
            <span class="invalid-feedback">
              <strong>{{ $errors->first('category_name') }}</strong>
            </span>
          @endif 
        </div>
        <div class="form-group col-md-4">
          
          <button type="submit" class="btn btn-primary btn-block">Submit</button>
        </div>
      </form>
    </div>
    

  </div>
  
</div>
<style type="text/css">
  .select_category .custom-control 
  {
    padding-left: 63px;   
  }
</style>
@endsection('content')

resources/views/admin/add-page.blade.php
@extends('layouts.admin-app')

@section('content')
<div class="xs-pd-20-10">
  <div class="min-height-200px">
    <div class="page-header">
      <div class="row">
        <div class="col-md-6 col-sm-12">
          <div class="title">
            <h4>Pages</h4>
          </div>
          <nav aria-label="breadcrumb" role="navigation">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{{route('admin.all_pages')}}">Pages</a></li>
              <li class="breadcrumb-item active" aria-current="page">Add New Page</li>
            </ol>
          </nav>
        </div>
        <div class="col-md-6 col-sm-12 text-right">
          <a class="btn btn-primary" href="{{route('admin.all_pages')}}" role="button">Back
          </a>
        </div>
      </div>
    </div>

    <!-- Select-2 Start -->
    <div class="pd-20 card-box mb-30">
      <div class="clearfix">
        <div class="pull-left">
          <h4 class="text-blue h4">Add New Page</h4>
          
        </div>
      </div>
      @if(session('error')) 
           <div class="alert alert-danger mb-4" role="alert"> <i class="flaticon-cancel-12 close" data-dismiss="alert"></i>{!! session('error') !!}</div>
            
           @endif
           @if(session('success')) 
           <div class="alert alert-success mb-4" role="alert"> 
            <i class="flaticon-cancel-12 close" data-dismiss="alert"></i>{!! session('success') !!}</div>
            
         @endif
      <form class="row" action="{{route('admin.new_page_post')}}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-group col-md-6">
          <label>*Page Title</label>
          <input class="form-control" name="page_title" value="{{old('page_title')}}" type="text" placeholder="Page title">
          @if ($errors->has('page_title'))
            <span class="invalid-feedback">
              <strong>{{ $errors->first('page_title') }}</strong>
            </span>
          @endif 
        </div>
        <div class="form-group col-md-12">
          <label>*Page Content</label>
          <input type="hidden" name="page_content" id="page_content">
          <div class="summernote"></div>
          @if ($errors->has('page_content'))
            <span class="invalid-feedback">
              <strong>{{ $errors->first('page_content') }}</strong>
            </span>
          @endif 
                  
        </div>
                
        <div class="form-group col-md-4">
          
          <button id="save" type="submit" class="btn btn-primary btn-block">Submit</button>
        </div>
      </form>
    </div>
    

  </div>
  
</div>
<style type="text/css">
  .flex_container_pd {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
}
.rte {
    margin-bottom: 15px;
}
.flex_container_pd > .flex_item_left_1_pd {
    width: 33%;
}
.flex_container_pd > .flex_item_right_2_pd {
    width: 67%;
    padding-left: 2%;
}
.rte table {
    table-layout: fixed;
}
table {
    border-collapse: collapse;
    border-spacing: 0;
    min-width: 50%;
}
th, td {
    text-align: left;
    padding: 15px;
    border: 1px solid #dedede;
}
.flex_container_pd_supporting {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
}
.flex_container_pd_supporting > .flex_item_pd_supporting {
    text-align: center;
    width: 20%;
}

a {
    color: #9c756f;
    text-decoration: none;
    background: transparent;
}
img.auto, .grid-item img, .grid-item iframe {
    max-width: 100%;
}
</style>
 
@endsection('content')

resources/views/admin/add-product.blade.php
@extends('layouts.admin-app')

@section('content')
<div class="xs-pd-20-10">
  <div class="min-height-200px">
    <div class="page-header">
      <div class="row">
        <div class="col-md-6 col-sm-12">
          <div class="title">
            <h4>Products</h4>
          </div>
          <nav aria-label="breadcrumb" role="navigation">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{{route('admin.products')}}">Products</a></li>
              <li class="breadcrumb-item active" aria-current="page">Add Product</li>
            </ol>
          </nav>
        </div>
        <div class="col-md-6 col-sm-12 text-right">
          <a class="btn btn-primary" href="{{route('admin.products')}}" role="button">Back
          </a>
        </div>
      </div>
    </div>

    <!-- Select-2 Start -->
    <div class="pd-20 card-box mb-30">
      <div class="clearfix">
        <div class="pull-left">
          <h4 class="text-blue h4">Add New Product</h4>
          
        </div>
      </div>
      @if(session('error')) 
           <div class="alert alert-danger mb-4" role="alert"> <i class="flaticon-cancel-12 close" data-dismiss="alert"></i>{!! session('error') !!}</div>
            
           @endif
           @if(session('success')) 
           <div class="alert alert-success mb-4" role="alert"> 
            <i class="flaticon-cancel-12 close" data-dismiss="alert"></i>{!! session('success') !!}</div>
            
         @endif
      <form class="row" action="{{route('admin.add_product_post')}}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-group col-md-6">
          <label>*Product Title</label>
          <input class="form-control" name="title" value="{{old('title')}}" type="text" placeholder="Product title">
          @if ($errors->has('title'))
            <span class="invalid-feedback">
              <strong>{{ $errors->first('title') }}</strong>
            </span>
          @endif 
        </div>
        <div class="form-group col-md-6">
          <label>*Price ($)</label>
          <input class="form-control" name="price" value="{{old('price')}}" type="text" placeholder="Product price in $">
          @if ($errors->has('price'))
            <span class="invalid-feedback">
              <strong>{{ $errors->first('price') }}</strong>
            </span>
          @endif 
                  
        </div>
        <div class="form-group col-md-6">
          <label>Quantity</label>
          <input class="form-control" name="quantity" value="{{old('quantity')}}" type="text" placeholder="Product quantity">
        </div>
        <div class="form-group col-md-6">
          <label>Description</label>
          <textarea name="description" placeholder="Product description" class="form-control">{{old('description')}}</textarea>
        </div>
        
        <div class="form-group col-md-6">
          <label>*Image</label>
          <input name="product_image" type="file" class="form-control-file form-control height-auto">
           @if ($errors->has('product_image'))
            <span class="invalid-feedback">
              <strong>{{ $errors->first('product_image') }}</strong>
            </span>
          @endif 
        </div>
        <div class="form-group">
          <h4 class="text-blue h4">Select Categories</h4>
          <div class="row select_category">
            
            <!-- <div class="col-md-6 col-sm-12"> -->
              
              @foreach($categories as $category)
              <div class="col-md-6 custom-control custom-checkbox mb-5">
                <input type="checkbox" name="category[]" class="custom-control-input" value="{{$category->id}}" id="customCheck{{$category->id}}-1">
                <label class="custom-control-label" for="customCheck{{$category->id}}-1">{{$category->name}}</label>
              </div>
              @endforeach
            <!-- </div> -->
            
          </div>
        </div>
        
        
        <div class="form-group col-md-4">
          
          <button type="submit" class="btn btn-primary btn-block">Submit</button>
        </div>
      </form>
    </div>
    

  </div>
  
</div>
<style type="text/css">
  .select_category .custom-control 
  {
    padding-left: 63px;   
  }
</style>
@endsection('content')

resources/views/admin/all-categories.blade.php
@extends('layouts.admin-app')

@section('content')
<div class="xs-pd-20-10">
	<div class="min-height-200px">
		<div class="page-header">
			<div class="row">
				<div class="col-md-6 col-sm-12">
					<div class="title">
						<h4>Categories</h4>
					</div>
					<nav aria-label="breadcrumb" role="navigation">
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Home</a></li>
							<li class="breadcrumb-item active" aria-current="page">Categories</li>
						</ol>
					</nav>
				</div>
				<div class="col-md-6 col-sm-12 text-right">
		         <a class="btn btn-primary" href="{{route('admin.add_category')}}" role="button">
		              Create Category
		         </a>
		      </div>
			</div>
		</div>
		<!-- Export Datatable start -->
		<div class="card-box mb-30">
			<div class="pd-20">
				<h4 class="text-blue h4">All Categories</h4>
			</div>
			<div class="pb-20">
				<table class="table hover multiple-select-row data-table-export nowrap">
					@if(count($categories)>0)
					<thead>
						<tr>
							<th class="table-plus datatable-nosort">#</th>
							<th>Name</th>
							<th>Products</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
						@foreach($categories as $category)
						<tr>
							<td>{{$loop->iteration}}</td>
							<td>{{$category->name}}</td>
							<td><a href="{{route('admin.category_products',$category->id)}}" class="btn btn-success">View Products</a></td>
							<td>
								<div class="dropdown">
                           <a class="btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                               <i class="dw dw-more"></i>
                           </a>
                           <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
                              <!--  <a class="dropdown-item" href="{{route('admin.product_details',$category->id)}}"><i class="dw dw-eye"></i> View</a> -->
                                <a class="dropdown-item" href="{{route('admin.category_edit',$category->id)}}"><i class="dw dw-edit2"></i> Edit</a>
                               <a class="dropdown-item" href="{{route('admin.category_delete',$category->id)}}"  onclick="return confirm('Are you sure to want delete this?')"><i class="dw dw-delete-3"></i> Delete</a> 
                           </div>
                       </div>
							</td>
						</tr>
						@endforeach
					</tbody>
					@endif
				</table>
			</div>
		</div>
		<!-- Export Datatable End -->
	</div>
</div>
@endsection('content')

resources/views/admin/all-pages.blade.php
@extends('layouts.admin-app')

@section('content')
<div class="xs-pd-20-10">
	<div class="min-height-200px">
		<div class="page-header">
			<div class="row">
				<div class="col-md-6 col-sm-12">
					<div class="title">
						<h4>Pages</h4>
					</div>
					<nav aria-label="breadcrumb" role="navigation">
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Home</a></li>
							<li class="breadcrumb-item active" aria-current="page">Pages</li>
						</ol>
					</nav>
				</div>
				<div class="col-md-6 col-sm-12 text-right">
		         <a class="btn btn-primary" href="{{route('admin.add_new_page')}}" role="button">
		              Create Page
		         </a>
		      </div>
			</div>
		</div>
		<!-- Export Datatable start -->
		<div class="card-box mb-30">
			<div class="pd-20">
				<h4 class="text-blue h4">All Pages</h4>
			</div>
			<div class="pb-20">
				<table class="data-table table stripe hover nowrap" data-page-length='50'>
					@if(count($allpages)>0)
					<thead>
						<tr>
							<th>#</th>
							<th>Page Name</th>
							<th>Status</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
						@foreach($allpages as $page)
						<tr>
							<td>{{$loop->iteration}}</td>
							<td>{{$page->title}}</td>
							<td>@if($page->status=='1')
								{{__('Active')}}
								@else
								{{__('Pending')}}
								@endif
							</td>
							<td>
								<div class="dropdown">
                           <a class="btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                               <i class="dw dw-more"></i>
                           </a>
                           <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
                               <a class="dropdown-item" href="{{route('pages_details',$page->slug)}}" target="_blank"><i class="dw dw-eye"></i> View</a>
                               <a class="dropdown-item" href="{{route('admin.page_edit',$page->id)}}"><i class="dw dw-edit2"></i> Edit</a>
                               <a class="dropdown-item" href="{{route('admin.page_delete',$page->id)}}"  onclick="return confirm('Are you sure to want delete this?')"><i class="dw dw-delete-3"></i> Delete</a>
                           </div>
                       </div>
							</td>
						</tr>
						@endforeach
					</tbody>
					@endif
				</table>
			</div>
		</div>
		<!-- Export Datatable End -->
	</div>
</div>
@endsection('content')

resources/views/admin/all-products.blade.php
@extends('layouts.admin-app')

@section('content')
<div class="xs-pd-20-10">
	<div class="min-height-200px">
		<div class="page-header">
			<div class="row">
				<div class="col-md-6 col-sm-12">
					<div class="title">
						<h4>Products</h4>
					</div>
					@if($pcview=='category')
					<nav aria-label="breadcrumb" role="navigation">
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="{{route('admin.categories')}}">Categories</a></li>
							<li class="breadcrumb-item active" aria-current="page">{{$category_name}}</li>
						</ol>
					</nav>


					@else
					<nav aria-label="breadcrumb" role="navigation">
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Home</a></li>
							<li class="breadcrumb-item active" aria-current="page">Products</li>
						</ol>
					</nav>
					@endif
				</div>
				<div class="col-md-6 col-sm-12 text-right">
		         <a class="btn btn-primary" href="{{route('admin.add_product')}}" role="button">
		              Create Product
		         </a>
		      </div>
			</div>
		</div>
		<!-- Export Datatable start -->
		<div class="card-box mb-30">
			<div class="pd-20">
				<h4 class="text-blue h4">{{$category_name}} All Products</h4>
			</div>
			<div class="pb-20">
				<table class="table hover multiple-select-row data-table-export nowrap">
					@if(count($products)>0)
					<thead>
						<tr>
							<th>#</th>
							<th class="table-plus datatable-nosort">Product</th>
							<th>Name</th>
							<th>Price</th>
							<th width="20%">Categories</th>
							<th>Status</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
						@foreach($products as $product)
						<tr>
							<td>{{$loop->iteration}}</td>
							<td class="table-plus">
                        <img src="{{ asset('')}}{{$product->image}}" width="70" height="70" alt="">
                     </td>
							<td>{{$product->title}}</td>
							<td>${{number_format($product->price,2)}}</td>
							<td>
								@if(isset($product->categories) && count($product->categories)>0)
								<i class="icon-copy fa fa-tag" aria-hidden="true"></i>
								@foreach($product->categories as $cat)
								<span class="badge badge-success" 
								style="font-size: 8px;">{{$cat->name}}</span>
									@if($loop->iteration %2==0)
									 <br/>
									@endif 
								@endforeach
								@endif
							</td>
							<td>@if($product->status=='1')
								{{__('Active')}}
								@else
								{{__('Pending')}}
								@endif
							</td>
							<td>
								<!-- <a href="{{route('admin.product_details',$product->id)}}" class="btn btn-primary">View</a> -->
								<div class="dropdown">
                           <a class="btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                               <i class="dw dw-more"></i>
                           </a>
                           <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
                               <a class="dropdown-item" href="{{route('admin.product_details',$product->id)}}"><i class="dw dw-eye"></i> View</a>
                               <a class="dropdown-item" href="{{route('admin.product_edit',$product->id)}}"><i class="dw dw-edit2"></i> Edit</a>
                               <a class="dropdown-item" href="{{route('admin.product_delete',$product->id)}}"  onclick="return confirm('Are you sure to want delete this?')"><i class="dw dw-delete-3"></i> Delete</a>
                           </div>
                       </div>
							</td>
						</tr>
						@endforeach
					</tbody>
					@endif
				</table>
			</div>
		</div>
		<!-- Export Datatable End -->
	</div>
</div>
@endsection('content')

resources/views/admin/category-edit.blade.php
@extends('layouts.admin-app')

@section('content')
<div class="xs-pd-20-10">
  <div class="min-height-200px mb-30">
    <div class="page-header">
      <div class="row">
        <div class="col-md-6 col-sm-12">
          <div class="title">
            <h4>Category</h4>
          </div>
          <nav aria-label="breadcrumb" role="navigation">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{{route('admin.categories')}}">Category</a></li>
              <li class="breadcrumb-item active" aria-current="page">Edit Category</li>
            </ol>
          </nav>
        </div>
        <div class="col-md-6 col-sm-12 text-right">
          <a class="btn btn-primary" href="{{route('admin.categories')}}" role="button">Back
          </a>
        </div>
      </div>
    </div>

    <!-- Select-2 Start -->
    <div class="pd-20 card-box mb-30">
      <div class="clearfix">
        <div class="pull-left">
          <h4 class="text-blue h4">Edit Category</h4>
          
        </div>
      </div>
      @if(session('error')) 
           <div class="alert alert-danger mb-4" role="alert"> <i class="flaticon-cancel-12 close" data-dismiss="alert"></i>{!! session('error') !!}</div>
            
           @endif
           @if(session('success')) 
           <div class="alert alert-success mb-4" role="alert"> 
            <i class="flaticon-cancel-12 close" data-dismiss="alert"></i>{!! session('success') !!}</div>
            
         @endif
      <form class="row" action="{{route('admin.category_update',$category_details->id)}}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-group col-md-12">
          <label>*Category Name</label>
          <input class="form-control" name="category_name" value="{{$category_details->name}}" type="text" placeholder="category name">
          @if ($errors->has('category_name'))
            <span class="invalid-feedback">
              <strong>{{ $errors->first('category_name') }}</strong>
            </span>
          @endif 
        </div>
        <div class="form-group col-md-4">
          <button type="submit" class="btn btn-primary btn-block">Update</button>
        </div>
      </form>
    </div>
    

  </div>
  
</div>
<style type="text/css">
  .select_category .custom-control 
  {
    padding-left: 63px;   
  }
</style>
@endsection('content')

resources/views/admin/left-sidebar.blade.php
<div class="left-side-bar">
		<div class="brand-logo">
			<a href="{{route('admin.dashboard')}}">
				<img src="{{ asset('public/admin/vendors/images/logo.png') }}" alt="" class="dark-logo">
				<img src="{{ asset('public/admin/vendors/images/logo-white.png') }}" alt="" class="light-logo">
			</a>
			<div class="close-sidebar" data-toggle="left-sidebar-close">
				<i class="ion-close-round"></i>
			</div>
		</div>
		<div class="menu-block customscroll">
			<div class="sidebar-menu">
				<ul id="accordion-menu">
					
					<li>
						<a href="{{route('admin.dashboard')}}" class="dropdown-toggle no-arrow">
							<span class="micon dw dw-house-1"></span>
							<span class="mtext">Dashboard</span>
						</a>
					</li>
					<li class="dropdown">
						<a href="javascript:;" class="dropdown-toggle">
							<span class="micon dw dw-trees"></span><span class="mtext">Products</span>
						</a>
						<ul class="submenu">
							<li><a href="{{route('admin.products')}}">All Products</a></li>
							<li><a href="{{route('admin.add_product')}}">Add New</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="javascript:;" class="dropdown-toggle">
							<span class="micon dw dw-tag"></span><span class="mtext">Categories</span>
						</a>
						<ul class="submenu">
							<li><a href="{{route('admin.categories')}}">All Categories</a></li>
							<li><a href="{{route('admin.add_category')}}">Add New</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="javascript:;" class="dropdown-toggle">
							<span class="micon dw dw-copy"></span>
							<span class="mtext">Product Documentation</span>
						</a>
						<ul class="submenu">
							<li><a href="{{route('admin.all_pages')}}">All Pages</a></li>
							<li><a href="{{route('admin.add_new_page')}}">Add New Page</a></li>
						</ul>
					</li>
					
					
				</ul>
			</div>
		</div>
	</div>