routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('frontend.index');
// });

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/collections', 'HomeController@getCollections')->name('collections');
Route::get('/products', 'HomeController@getCollections');
Route::get('/search', 'HomeController@getSearchProducts')->name('product_search');
Route::get('/collections/{slug}', 'HomeController@getCollectionProducts')->name('collection_products');
Route::get('/products/{slug}', 'HomeController@getProductDetail')->name('product_details');
Route::get('/collections/pages/{slug}', 'HomeController@getPagesDetail')->name('pages_details');
Route::post('/products/add-to-cart', 'HomeController@addToCart')->name('add_to_cart');
Route::get('cart', 'HomeController@myShoppingCart')->name('my_cart');
Route::post('remove-from-cart', 'HomeController@removeFromCart');
Route::post('update-cart', 'HomeController@updateCart');
Route::get('checkout', 'HomeController@cartCheckout')->name('checkout');


Route::group(['as'=>'admin.','prefix' => 'admin','namespace'=>'Admin','middleware'=>['auth','admin']], function () {
		Route::get('dashboard', 'DashboardController@index')->name('dashboard');
		Route::get('products/add', 'DashboardController@addProduct')->name('add_product');
		Route::post('products/add', 'DashboardController@addProductPost')->name('add_product_post');
		Route::get('products', 'DashboardController@allProducts')->name('products');
		Route::get('products/{id}', 'DashboardController@getProductDetails')->name('product_details');
		Route::get('products/{id}/edit', 'DashboardController@getProductEdit')->name('product_edit');
		Route::post('products/{id}/edit', 'DashboardController@productUpdate')->name('product_update');
		Route::get('products/{id}/delete', 'DashboardController@deletProduct')->name('product_delete');
		Route::get('categories', 'DashboardController@allCategories')->name('categories');
		Route::get('category/{id}/products', 'DashboardController@getCategoryProducts')->name('category_products');

		Route::get('category/{id}/delete', 'DashboardController@deleteCategory')->name('category_delete');
		Route::get('category/add', 'DashboardController@addCategory')->name('add_category');
		Route::post('category/add', 'DashboardController@addCategoryPost')->name('add_category_post');

		Route::get('category/{id}/edit', 'DashboardController@getCategoryEdit')->name('category_edit');
		Route::post('category/{id}/edit', 'DashboardController@categoryUpdate')->name('category_update');

		Route::get('all-pages', 'DashboardController@productDocumentationPages')->name('all_pages');
		Route::get('add-new-page', 'DashboardController@addNewPage')->name('add_new_page');
		Route::post('add-new-page', 'DashboardController@addNewPagePost')->name('new_page_post');

		Route::get('page/{id}', 'DashboardController@getPageEdit')->name('page_edit');
		Route::post('page/{id}', 'DashboardController@pageUpdatePost')->name('page_update');
		Route::get('page/{id}/delete', 'DashboardController@deletePage')->name('page_delete');



});

Route::group(['as'=>'user.','prefix' => 'user','namespace'=>'User','middleware'=>['auth','user']], function () {
		Route::get('my-account', 'DashboardController@myAccount')->name('my_account');
		Route::post('my-account', 'DashboardController@updateUserPost')->name('update_account');
		Route::get('change-password', 'DashboardController@changePassword')->name('change_password');
		Route::post('change-password', 'DashboardController@changePasswordPost')->name('update_password');

		Route::post('pay-now', 'PayPalController@makepayment')->name('make_payment');
		Route::get('payment/success', 'PayPalController@success')->name('payment.success');
		Route::get('payment/cancel', 'PayPalController@cancel')->name('payment.cancel');

		Route::get('transactions', 'PayPalController@transactionHistory')->name('transaction_history');
		Route::get('transactions/{id}', 'PayPalController@transactionDetails')->name('transaction_detail');
});


Route::group(['as'=>'pages.','prefix' => 'pages'], function () {
		Route::get('news', 'PagesController@news')->name('news');
		Route::get('product-documentation', 'PagesController@productDocumentation')->name('product_documentation');
		Route::get('contact-us', 'PagesController@contactUs')->name('contact_us');
		Route::post('contact-us', 'PagesController@contactPost')->name('contact_post');
		Route::get('terms-conditions', 'PagesController@termsAndConditions')->name('terms_conditions');
		Route::get('faq', 'PagesController@faq')->name('faq');
		
		Route::get('about-us', 'PagesController@aboutUs')->name('about_us');
});

app/Http/Controllers/User/DashboardController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Rules\MatchOldPassword;
use App\Country;
use App\User;
use Auth, Hash;
class DashboardController extends Controller
{
   public function myAccount()
   {
   	$countries=Country::all();
   	return view('user.my-account',compact('countries'));
   }
   public function updateUserPost(Request $request)
   {
   	//echo "<pre>";print_r($request->all());die;
   	$user_id=Auth::user()->id;
   	$this->validate($request,[
                'first_name'=>'required',
                'last_name'=>'required',
                'company' => 'required',
                'address1' => 'required',
                'address2' => 'required',
                'city' => 'required',
                'country' => 'required',
                'zip_code' => 'required',
                'phone' => 'required',
               ]);
   	
   	$user=User::find($user_id);
   	$user->first_name=$request->first_name;
   	$user->last_name=$request->last_name;
   	$user->company=$request->company;
   	$user->address1=$request->address1;
   	$user->address2=$request->address2;
   	$user->city=$request->city;
   	$user->country=$request->country;
   	$user->zip_code=$request->zip_code;
   	$user->phone=$request->phone;
   	if($user->save())
   	{
   		$message="You have successfully updated your account details !!!";
      	return redirect()->back()->with(['success' => $message]);
   	}

   }
   public function changePassword()
   {
   	return view('user.change-password');
   }
   public function changePasswordPost(Request $request)
   {
   	 $request->validate([
          'current_password' => 'required',
          'password' => 'required|string|min:6|confirmed',
          'password_confirmation' => 'required',
        ]);

        $user = Auth::user();

        if (!Hash::check($request->current_password, $user->password)) {
            return back()->with('error', 'Current password does not match!');
        }

        $user->password = Hash::make($request->password);
        $user->save();

        return back()->with('success', 'Password successfully changed!');

   }
  /* public function myOrders()
   {
   	$countries=Country::all();
   	return view('user.my-account',compact('countries'));
   }*/

}

app/Http/Controllers/User/PayPalController.php
<?php
  
namespace App\Http\Controllers\User;
  
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use App\Http\Controllers\Controller;
use Srmklive\PayPal\Services\ExpressCheckout;
use App\User;
use App\Order; 
use App\OrderDetail; 
use App\Product;
use App\Category;
use App\Page;
use App\UserShipping;
use App\Country;
use Illuminate\Support\Facades\Auth;
use DB;
use Carbon\Carbon;
use Response;  
use Log;
use DateTime;
class PayPalController extends Controller
{
    /**
     * Responds with a welcome message with instructions
     *
     * @return \Illuminate\Http\Response
     */
        
    public function makepayment(Request $request)
    {
    	//echo "<pre>";print_r(session()->get('cart'));die;
        if(Auth::check())
        {
            $user_id=Auth::user()->id;

            $data = [];
            $cart = session()->get('cart');
            //echo "<pre>";print_r($cart);//print_r($cart['review_section_1']);
            
            
            if(isset($cart['product']) && count($cart['product'])>0)
            {
                $this->validate($request, [
                'first_name' => 'required',
                'last_name'=>'required',
                'address' => 'required',
                'apartment' => 'required',
                'phone' => 'required',
                'city'=> 'required',
                'country'=> 'required',
                'state'=> 'required',
                'zipcode'=> 'required'
                ]);
                $usershippings=array();
                $usershippings['first_name']=$request->first_name;
                $usershippings['last_name']=$request->last_name;
                $usershippings['address']=$request->address;
                $usershippings['apartment']=$request->apartment;
                $usershippings['phone']=$request->phone;
                $usershippings['city']=$request->city;
                $usershippings['country']=$request->country;
                $usershippings['state']=$request->state;
                $usershippings['zipcode']=$request->zipcode;
                $usershippings['user_id']=$user_id;
                $shippings=UserShipping::where('user_id',$user_id)->first();
                if(!empty($shippings))
                {
                    $shippings->update($usershippings);
                }
                else
                {
                    UserShipping::create($usershippings);
                }
                $Order=new Order;
                $Order['amount']=0;
                $Order['user_id']=$user_id;
                $Order->save();

                $data=$this->addOrderDetails($Order->id);
                

                $user_order=Order::find($Order->id);
                $user_order->amount =number_format($data['total_price'],2);
                $user_order->save();
                $data['invoice_id'] = $user_order->id;
            }
            else
            {
                $message="Please add at least one item";
                return redirect()->route('collections')
                    ->with('error',$message);
            }
           //echo "<pre>";print_r($data);
            $data['invoice_description'] = "Order #{$data['invoice_id']} Invoice";
            $data['return_url'] = route('user.payment.success');
            $data['cancel_url'] = route('user.payment.cancel');
            $data['total'] = number_format($data['total_price'],2);
            $request->session()->put('order_id', $data['invoice_id']);
            $provider = new ExpressCheckout;
      
            $response = $provider->setExpressCheckout($data);
      
            //$response = $provider->setExpressCheckout($data, true);
            //echo "<pre>";print_r($response);die;
            return redirect($response['paypal_link']);
        }
        else
        {
        		return redirect()->route('login');
        }
    }
   
    public function addOrderDetails($order_id)
    {
        $data = [];
        
        $total_price=0;
        $cart = session()->get('cart');
        $user_id=Auth::user()->id;
        if(isset($cart['product']))
        {   $products=array();
            foreach ($cart['product'] as $key => $value) 
            {
                $arr_item=array();
                $arr_item['name']=$value['title'];
                $arr_item['price']=$value['price'];
                $arr_item['qty']=$value['qty'];
                $data['items'][] =$arr_item;
                $total_price +=$value['price']*$value['qty'];
                
                 array_push($products, $value['id']);

                $OrderDetail= new OrderDetail;
                $OrderDetail['product_id']=$value['id'];
                $OrderDetail['order_id']=$order_id;
                $OrderDetail['qty']=$value['qty'];
                $OrderDetail['price']=$value['price'];
                $OrderDetail['subtotal']=$value['price']*$value['qty'];
                $OrderDetail->save();
            }

        }
        
        $data['total_price']=$total_price;
        return $data;
        
    }
   
    /**
     * Responds with a welcome message with instructions
     *
     * @return \Illuminate\Ht*tp\Response
     */
    public function cancel(Request $request)
    {
        //dd('Your payment is canceled. You can create cancel page here.');
        $order_id = session()->get('order_id');
        if(!empty($order_id))
        {
            $userOrder = Order::find($order_id);
            if(!empty($request->query('token')))
            {
                $userOrder->payment_id=$request->query('token');
            }
            $userOrder->status='3';
            $userOrder->save();
            $request->session()->forget('cart');
            return redirect('/user/transactions/'.$order_id)->withError('Payment is canceled !!!');
        }
        else
        {
            $request->session()->forget('cart');
            return redirect('/cart')->withError('Payment is canceled !!!');
        }
        

    }
  
    /**
     * Responds with a welcome message with instructions
     *
     * @return \Illuminate\Http\Response
     */
    public function success(Request $request)
    {
      //echo "<pre>";print_r($request->all());die;
        $order_id = session()->get('order_id');
        if (empty($request->query('PayerID')) || empty($request->query('token')))
        {
            $userOrder = Order::find($order_id);
            $userOrder->status='2';
            $userOrder->save();
            return redirect('/user/transactions/'.$order_id)->withError('Payment was not successful. Please Try Again !!');
        }

        $provider = new ExpressCheckout;
        $response = $provider->getExpressCheckoutDetails($request->token);

        //echo "<pre>";print_r($response);
        	if (in_array(strtoupper($response['ACK']), ['SUCCESS', 'SUCCESSWITHWARNING'])) 
        	{
            if(isset($order_id))
            {
               $transactions = Order::where('id',$order_id)
                    ->with('orderdetail')
                    ->first();
                   
               $transactions->payment_id=$request->query('token');
               $transactions->payer_id=$request->query('PayerID');
               $transactions->status='1';
               $transactions->save();
            }
         	$request->session()->forget('cart');
         	return redirect('user/transactions/'.$order_id)->withSuccess('Payment made successfully.');
        }
        else
        {
            $userOrder = Order::find($order_id);
            $userOrder->status='2';
            $userOrder->save();
            return redirect('/user/transactions/'.$order_id)->withError('Payment authentication problem. Please Try Again !!');
        }
  
       // dd('Something is wrong.');
    }
    public function getTransactionid($provider,$transaction)
    {
        //echo "<pre>";print_r($transaction->subscriptiondetail[0]['plan']);die;
        $data=array();
        $arr_item=array();
        if($transaction->plan_type=='2')
        {
            if(isset($transaction->subscriptiondetail[0]['plan']) && $transaction->subscriptiondetail[0]['plan'] =='1')
            {
                $arr_item['name']='Monthly Unlimited';
                $arr_item['price']='24.99';
            }
            else if(isset($transaction->subscriptiondetail[0]['plan']) && $transaction->subscriptiondetail[0]['plan'] =='2')
            {
                $arr_item['name']='Yearly Unlimited';
                $arr_item['price']='199.00';
            }
            
        }
        
        $arr_item['qty']='1';
        $data['items'][] =$arr_item;
        $data['invoice_id'] = $transaction->id;
        $data['invoice_description'] = "Order #{$transaction->id} Invoice";
        $data['total'] = number_format($transaction->amount,2);
        $responses = $provider->doExpressCheckoutPayment($data, $_GET['token'], $_GET['PayerID']);
        //echo "<pre>";print_r($responses);die;
        return $responses['PAYMENTINFO_0_TRANSACTIONID'];
    }
    public function transactionHistory()
    {
        if(Auth::check())
        {
            $user_id=Auth::user()->id;
            $ordertransactions = Order::where('user_id',$user_id)
             ->with('orderdetail')
             ->orderBy('id','DESC')
             ->get();
            //echo "<pre>";print_r($ordertransactions->toArray());die;
            foreach ($ordertransactions as $key => $transactions) 
            {
                if(isset($transactions->orderdetail))
                {
                  	$transactions['test_detail']='';
                   // echo "<pre>";print_r($transactions->orderdetail);die;
                  	foreach ($transactions->orderdetail as $key => $value) 
                  	{
                     	$productdetails=Product::where('id',$value->product_id)->first();
              			$arr=$productdetails->toArray();
                        if(isset($transactions->orderdetail[$key]->product))

resources/views/user/change-password.blade.php
@extends('layouts.frontend-app')

@section('content')
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
    <div class="breadcrumb"><a href="{{route('home')}}">Home</a> <span>></span> Change Password</div>
    </div>
    </div>
  </div>
</section>
<section class="contentSection">
  <div class="container">
    <div class="row">
      @include('user.left-sidebar')
    <div class="col-md-8 col-lg-9">
      <h2>Change Password</h2>
      <div class="cartBlock">
        <form method="POST" action="{{ route('user.update_password') }}">
          @csrf
          @if(session('error')) 
            <div class="col-md-12 error alert alert-danger alert-dismissable">
              <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
              <strong>Error : </strong>   {{ session('error') }}
            </div>
          @endif
          @if(session('success')) 
            <div class="col-md-12 error alert alert-success alert-dismissable">
              <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {!! session('success') !!}
            </div>
          @endif
          <div class="row">
            <div class="col-md-6">
              <label for="current_password">Current Password</label> 
              <input id="current_password" type="password" class="@error('current_password') is-invalid @enderror" name="current_password" value="{{ old('current_password')}}" autocomplete="current_password" autofocus>
              @error('current_password')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
              @enderror
            </div>
            <div class="col-md-6">
              <label for="password">New Password</label> 
              <input id="password" type="password" class="@error('password') is-invalid @enderror" name="password" value="{{ old('password') }}"  autocomplete="password">
              @error('password')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
              @enderror
            </div>
            <div class="col-md-6">
              <label for="password_confirmation">Confirm New Password</label> 
              <input id="password_confirmation" type="text" class="@error('password_confirmation') is-invalid @enderror" name="password_confirmation" autocomplete="password_confirmation" >
              @error('password_confirmation')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
              @enderror
            </div>
            
          </div>
          <input type="submit" value="Update" class="submitBtn">
        </form>
      </div>
    </div>
  </div>
</div>
</section>
@endsection('content')

resources/views/user/left-sidebar.blade.php
<div class="col-md-4 col-lg-3">
 <!--  <div class="userImage"><img src="images/Howard-Field-small.png" class="imgResponsive" > </div> -->
  <h3 class="userName">{{ Auth::user()->name }}</h3>
  <hr class="d-block">
  <ul class="userSettingList">
    <li class="active"><a href="{{route('user.my_account')}}"><i class="fa fa-user-o" aria-hidden="true"></i> My Account</a></li>
    <!-- <li><a href="#"><i class="fa fa-bell-o" aria-hidden="true"></i> Notifications</a></li> -->
    <li><a href="{{route('user.change_password')}}"><i class="fa fa-key" aria-hidden="true"></i> Change Password</a></li>
    <!-- <li><a href="#"><i class="fa fa-shopping-basket" aria-hidden="true"></i> My Wishlist</a></li> -->
    <li><a href="{{route('user.transaction_history')}}"><i class="fa fa-list-ul" aria-hidden="true"></i> My Order</a></li>
    <li>
      <a href="{{ route('logout') }}"  onclick="event.preventDefault();document.getElementById('logout-form').submit();"> <i class="fa fa-power-off" aria-hidden="true"></i> {{ __('Logout') }}
          </a>
      
    </li>
  </ul>
</div>

resources/views/user/my-order.blade.php
@extends('layouts.frontend-app')

@section('content')
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
    <div class="breadcrumb"><a href="{{route('home')}}">Home</a> <span>></span> Login</div>
    </div>
    </div>
  </div>
</section>
<section class="contentSection">
  <div class="container">
    <div class="row">
      @include('user.left-sidebar')
    <div class="col-md-8 col-lg-9">
      <h2>Order History</h2>
      <div class="cartBlock">
        <table class="table table-striped cart w-100">
          <thead>
            <tr>
              <th scope="col">Order ID</th>
              <th scope="col">Order Date</th>
              <th scope="col">Order Number</th>
              <th scope="col">Status</th>
            </tr>
          </thead>
          <tbody>
              <tr>
                <td>1</td>
                <td>16-11-2021</td>
                <td>USA1324789012</td>
                <td class="text-success"><strong>Deliverd</strong></td>
              </tr>
              <tr>
                <td>2</td>
                <td>16-11-2021</td>
                <td>USA1324789012</td>
                <td class="text-danger"><strong>Pending</strong></td>
              </tr>
              <tr>
                <td>3</td>
                <td>16-11-2021</td>
                <td>USA1324789012</td>
                <td><strong>In Process</strong></td>
              </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</section>
@endsection('content')

resources/views/user/order-detail.blade.php
@extends('layouts.frontend-app')

@section('content')

<section class="contentSection">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
	     <!--  <h2>Invoice</h2> -->
        <div class="mt-5 text-center">
          <h1 class="display-4 mb-3">Invoice</h1>
         
        </div>
        <div class="row">
          <div class="col-md-6 text-left">
           <p class="lead">
            <strong>Payment ID:- </strong> {{$transactions->payment_id}}</p>
            <p class="lead">
            <strong>Invoice ID:- </strong> {{$transactions->id}}</p>
            <p class="lead">
            <strong>Date:- </strong> {{date_format($transactions->created_at, 'F j, Y')}}</p>
          </div>
          <div class="col-md-6 mt-5 mb-5 text-right">
            <p class="lead">
              <strong>Status:- </strong>
              @if($transactions->status=='1')
                <badge class="btn-sm btn-success">Success</badge>
              @elseif($transactions->status=='2')
                <badge class="btn-sm btn-info">Fail</badge>
              @elseif($transactions->status=='3')
                <badge class="btn-sm btn-danger">Cancel</badge>
              @else
                <badge class="btn-sm btn-secondary">Pending</badge>
              @endif
            </p>      
            <p class="lead">
            <strong>Name:- </strong> {{$transactions->user->first_name .' '.$transactions->user->last_name}}</p>
          </div>
        </div>
        <hr>
		    <div class="cartBlock">
          <table class="table table-striped cart w-100">
            <thead>
              <tr>
				        <th scope="col">#</th>
                <th scope="col">Product</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
                <th scope="col">Sub Total</th>
              </tr>
            </thead>
            <tbody>
              @if(isset($transactions->orderdetail) && count($transactions->orderdetail)>0)
              @foreach($transactions->orderdetail as $key=>$order)
              <tr>
				        <td>{{$loop->iteration}}</td>
                <td>{{ $transactions->product[$key]['title']}}</td>
                <td>${{$order->price}}</td>
                <td>{{$order->qty}}</td>
                <td class="text-success"><strong>${{number_format($order->price * $order->qty, 2)}}</strong></td>

              </tr>
              @endforeach
               <tr>
                 <td colspan="4" class="text-right"><b>Total</b></td>
                 <td class="text-success"><strong>${{$transactions->amount}}</strong></td>
               </tr>
              @endif
              
            </tbody>
          </table>

          <div class="mt-5 mb-5 text-center">
          <h1 class="display-4 mb-3">Thank You!</h1>
         
          <p class="mt-4">
            Having trouble? <a href="{{route('pages.contact_us')}}">Contact us</a>
          </p>
          <p class="lead">
            <a href="{{route('user.transaction_history')}}" class="ml-1 mr-1 customBtn01 transparentBtn">All Transactions</a> 
            <a href="{{route('collections')}}" class="ml-1 mr-1 customBtn01">Continue Shopping</a>
          </p>
        </div>

        </div>
		  </div>
    </div>
  </div>
</section>
@endsection('content')

resources/views/user/transactions.blade.php
@extends('layouts.frontend-app')

@section('content')

<section class="contentSection">
  <section>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="breadcrumb"><a href="{{route('user.my_account')}}">My Account</a> <span>></span>Order History</div>
      </div>
    </div>
  </div>
</section>

  <div class="container">
    <div class="row">
      <div class="col-md-12">
	       <h2>Order History</h2>
		    <div class="cartBlock">
          <table class="table table-striped cart w-100">
            <thead>
              <tr>
				        <th scope="col">#</th>
                <th scope="col">Payment ID</th>
                <th scope="col">Payer ID</th>
                <th scope="col">Amount</th>
                <th scope="col">Order Date</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
              @foreach($ordertransactions as $order)
              <tr>
				        <td>{{$loop->iteration}}</td>
                <td>{{$order->payment_id}}</td>
                <td>{{$order->payer_id}}</td>
                <td>${{$order->amount}}</td>
                <td>{{ date_format($order->created_at, 'F j, Y') }}</td>
                <td class="text-success">
                  @if($order->status=='1')
                    <badge class="btn-sm btn-success">Success</badge>
                  @elseif($order->status=='2')
                    <badge class="btn-sm btn-info">Fail</badge>
                  @elseif($order->status=='3')
                    <badge class="btn-sm btn-danger">Cancel</badge>
                  @else
                    <badge class="btn-sm btn-secondary">Pending</badge>
                  @endif
                </td>
                <td><a href="{{route('user.transaction_detail',$order->id)}}" class="btn btn-info">View</a></td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
		  </div>
    </div>
  </div>
</section>
@endsection('content')