routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('frontend.index');
// });

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/collections', 'HomeController@getCollections')->name('collections');
Route::get('/products', 'HomeController@getCollections');
Route::get('/search', 'HomeController@getSearchProducts')->name('product_search');
Route::get('/collections/{slug}', 'HomeController@getCollectionProducts')->name('collection_products');
Route::get('/products/{slug}', 'HomeController@getProductDetail')->name('product_details');
Route::get('/collections/pages/{slug}', 'HomeController@getPagesDetail')->name('pages_details');
Route::post('/products/add-to-cart', 'HomeController@addToCart')->name('add_to_cart');
Route::get('cart', 'HomeController@myShoppingCart')->name('my_cart');
Route::post('remove-from-cart', 'HomeController@removeFromCart');
Route::post('update-cart', 'HomeController@updateCart');
Route::get('checkout', 'HomeController@cartCheckout')->name('checkout');


Route::group(['as'=>'admin.','prefix' => 'admin','namespace'=>'Admin','middleware'=>['auth','admin']], function () {
		Route::get('dashboard', 'DashboardController@index')->name('dashboard');
		Route::get('products/add', 'DashboardController@addProduct')->name('add_product');
		Route::post('products/add', 'DashboardController@addProductPost')->name('add_product_post');
		Route::get('products', 'DashboardController@allProducts')->name('products');
		Route::get('products/{id}', 'DashboardController@getProductDetails')->name('product_details');
		Route::get('products/{id}/edit', 'DashboardController@getProductEdit')->name('product_edit');
		Route::post('products/{id}/edit', 'DashboardController@productUpdate')->name('product_update');
		Route::get('products/{id}/delete', 'DashboardController@deletProduct')->name('product_delete');
		Route::get('categories', 'DashboardController@allCategories')->name('categories');
		Route::get('category/{id}/products', 'DashboardController@getCategoryProducts')->name('category_products');

		Route::get('category/{id}/delete', 'DashboardController@deleteCategory')->name('category_delete');
		Route::get('category/add', 'DashboardController@addCategory')->name('add_category');
		Route::post('category/add', 'DashboardController@addCategoryPost')->name('add_category_post');

		Route::get('category/{id}/edit', 'DashboardController@getCategoryEdit')->name('category_edit');
		Route::post('category/{id}/edit', 'DashboardController@categoryUpdate')->name('category_update');

		Route::get('all-pages', 'DashboardController@productDocumentationPages')->name('all_pages');
		Route::get('add-new-page', 'DashboardController@addNewPage')->name('add_new_page');
		Route::post('add-new-page', 'DashboardController@addNewPagePost')->name('new_page_post');

		Route::get('page/{id}', 'DashboardController@getPageEdit')->name('page_edit');
		Route::post('page/{id}', 'DashboardController@pageUpdatePost')->name('page_update');
		Route::get('page/{id}/delete', 'DashboardController@deletePage')->name('page_delete');



});

Route::group(['as'=>'user.','prefix' => 'user','namespace'=>'User','middleware'=>['auth','user']], function () {
		Route::get('my-account', 'DashboardController@myAccount')->name('my_account');
		Route::post('my-account', 'DashboardController@updateUserPost')->name('update_account');
		Route::get('change-password', 'DashboardController@changePassword')->name('change_password');
		Route::post('change-password', 'DashboardController@changePasswordPost')->name('update_password');

		Route::post('pay-now', 'PayPalController@makepayment')->name('make_payment');
		Route::get('payment/success', 'PayPalController@success')->name('payment.success');
		Route::get('payment/cancel', 'PayPalController@cancel')->name('payment.cancel');

		Route::get('transactions', 'PayPalController@transactionHistory')->name('transaction_history');
		Route::get('transactions/{id}', 'PayPalController@transactionDetails')->name('transaction_detail');
});


Route::group(['as'=>'pages.','prefix' => 'pages'], function () {
		Route::get('news', 'PagesController@news')->name('news');
		Route::get('product-documentation', 'PagesController@productDocumentation')->name('product_documentation');
		Route::get('contact-us', 'PagesController@contactUs')->name('contact_us');
		Route::post('contact-us', 'PagesController@contactPost')->name('contact_post');
		Route::get('terms-conditions', 'PagesController@termsAndConditions')->name('terms_conditions');
		Route::get('faq', 'PagesController@faq')->name('faq');
		
		Route::get('about-us', 'PagesController@aboutUs')->name('about_us');
});

resources/views/pages/about-us.blade.php
@extends('layouts.frontend-app')

@section('content')
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
    <div class="breadcrumb"><a href="{{route('home')}}">Home</a> <span>></span> ABOUT US</div>
    </div>
    </div>
  </div>
</section>
<section class="contentSection">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>ABOUT US</h1>


            <h3>Greenfield is the largest high-purity alcohol company in North America offering bulk and packaged ingredients and additives. Under the Pharmco brand, we offer a wide range of specialty alcohols and bio-based chemicals to quality-driven and environmentally-conscious customers around the globe. The Pharmco brand has come to stand for premium quality and service excellence. We have been supplying life science, food, flavor, fragrance, personal care, extraction and industrial companies with mission-critical products for more than 30 years.</h3>

            <h3>Businesses ranging from start-ups to the largest companies in the world trust Pharmco with their specialty chemical and ingredient needs because Pharmco provides:</h3>
            <ul class="listing01">
            <li>A level of quality and service that small suppliers can’t replicate and large suppliers can’t react to. We are not simply brokers. We control the process from order receipt to manufacturing to delivery.</li>
            <li>A personal touch. We know our customers and provide extraordinary access to our internal team to make sure your needs are met.</li>
            <li>Certifications and standards including GMP, Organic, Non-GMO Project Verified, and ISO 9001:2015. Our products are tested and certified to meet requirements of United States Pharmacopeia, European Pharmacopeia, Japanese Pharmacopeia, American Chemical Society and Food Chemical Codex monographs, as well as other federal and custom specifications..</li>
            <li>Lab capabilities ranging from simple wet chemistry to sophisticated metals testing on our inductively coupled plasma mass spectrometry (ICP-MS) instruments.</li>
            <li>Twelve federally registered Distilled Spirits Plant (DSP) locations offering regional distribution from coast to coast and through more than 40 international distribution partners.</li>
            <li>An unbroken chain of custody for ethanol supplied from our parent producer, Greenfield Global.</li>
            <li>Sterile and bio-friendly solvents and bioprocess solutions.</li>
            <li>Custom ethanol cuts and the widest range of alcohol formulas and solvent blends.</li>
            <li>Product scale-up from kilos to metric tons, with package sizes ranging from pints to railcars.</li>
            <li>A commitment to reducing our global reliance on fossil fuels and petroleum-based products.</li>
            </ul>


      </div>
    </div>
  </div>
</section>
@endsection('content')

resources/views/pages/checkout.blade.php
@extends('layouts.frontend-app')

@section('content')
<section class="contentSection shippingPageContent">
  <div class="container">
    <div class="row">
      <div class="col-md-6 order-md-1 order-12">
        <form action="{{route('user.make_payment')}}" method="post">
          @csrf
        <div>
          <h2>Shipping Address</h2>
          
            <div class="row">
              <div class="col-lg-6">
                <label for="firstname">First Name</label>
                <input type="text" id="text" name="first_name" value="{{(isset($shippings->first_name) && $shippings->first_name !='')? $shippings->first_name:old('first_name')}}">
                @error('first_name')
                 <span class="invalid-feedback" role="alert">
                     <strong>{{ $message }}</strong>
                 </span>
               @enderror
              </div>
              <div class="col-lg-6">
                <label for="lastname">Last Name</label>
                <input type="text" id="text" name="last_name" value="{{(isset($shippings->last_name) && $shippings->last_name !='')? $shippings->last_name:old('last_name')}}">
                @error('last_name')
                 <span class="invalid-feedback" role="alert">
                     <strong>{{ $message }}</strong>
                 </span>
               @enderror
              </div>
              <div class="col-md-12">
                <label for="Email">Address</label>
                <input type="text" id="text" name="address" value="{{(isset($shippings->address) && $shippings->address !='')? $shippings->address:old('address')}}">
                @error('address')
                 <span class="invalid-feedback" role="alert">
                     <strong>{{ $message }}</strong>
                 </span>
               @enderror
              </div>
              <div class="col-md-6">
                <label for="apt">Apartment, Suite, etc.</label>
                <input type="text" id="apt" name="apartment" value="{{(isset($shippings->apartment) && $shippings->apartment !='')? $shippings->apartment:old('apartment')}}">
                @error('apartment')
                 <span class="invalid-feedback" role="alert">
                     <strong>{{ $message }}</strong>
                 </span>
               @enderror
              </div>
              <div class="col-md-6">
                <label for="phone">Phone</label>
                <input type="text" id="phone" name="phone" value="{{(isset($shippings->phone) && $shippings->phone !='')? $shippings->phone:old('phone')}}">
                @error('phone')
                 <span class="invalid-feedback" role="alert">
                     <strong>{{ $message }}</strong>
                 </span>
               @enderror
              </div>
              <div class="col-md-12">
                <label for="city">City</label>
                <input type="text" id="city" name="city" value="{{(isset($shippings->city) && $shippings->city !='')? $shippings->city:old('city')}}">
                @error('city')
                 <span class="invalid-feedback" role="alert">
                     <strong>{{ $message }}</strong>
                 </span>
               @enderror
              </div>
              <div class="col-lg-4">
                <label for="country">Country</label>
                <select name="country" id="country" >
                @foreach($countries as $country)
                  <option value="{{$country->id}}" {{((isset($shippings->country) && $shippings->country==$country->id) || old('county')==$country->id)?"selected":''}}>{{$country->name}}</option>
                @endforeach
              </select>
                @error('country')
                 <span class="invalid-feedback" role="alert">
                     <strong>{{ $message }}</strong>
                 </span>
               @enderror
              </div>
              <div class="col-lg-4">
                <label for="state">State</label>
                <input type="text" id="state" name="state" value="{{(isset($shippings->state) && $shippings->state !='')? $shippings->state:old('state')}}">
                @error('state')
                 <span class="invalid-feedback" role="alert">
                     <strong>{{ $message }}</strong>
                 </span>
               @enderror
              </div>
              <div class="col-lg-4">
                <label for="zipcode">Zipcode</label>
                <input type="text" id="zipcode" name="zipcode" value="{{(isset($shippings->zipcode) && $shippings->zipcode !='')? $shippings->zipcode:old('zipcode')}}">
                @error('zipcode')
                 <span class="invalid-feedback" role="alert">
                     <strong>{{ $message }}</strong>
                 </span>
               @enderror
              </div>
            </div>
         
        </div>
        <div class="cartFinalInfo">
          <div>
            <a href="{{route('my_cart')}}" class="ml-1 mr-1 customBtn01 transparentBtn">Return to Cart</a> 
            <a href="{{route('collections')}}" class="ml-1 mr-1 customBtn01">Continue Shopping</a></div>
        </div>
      </div>
      <div class="col-md-6 order-md-12 order-1">
        <h2>Shopping Cart</h2>
        <div class="cartBlock">
          @if(isset($cartitems['product']) && count($cartitems['product'])>0)
          <table class="table table-striped cart w-100">
            <thead>
              <tr>
                <th scope="col">Item Name</th>
                <th scope="col">Qty</th>
                <th scope="col">Price</th>
                <th scope="col" class="text-right">Total Price</th>
              </tr>
            </thead>
            <tbody>
              @php 
                $total_price=0;
              @endphp
              @foreach($cartitems['product'] as $item)
              <tr>
                <td>
                  <div class="cartProductInfo d-flex">
                    <div class="cartThumb"><img src="{{asset($item['image'])}}" alt=""></div>
                    <p>{{$item['title']}} <br>
                      <span class="removeButton"><a href="#" onclick="removeProduct({{$item['id']}})">Remove</a></span></p>
                  </div>
                </td>
                <td>{{$item['qty']}}</td>
                <td>{{$item['price']}}</td>
                <td class="price">${{$item['qty']*$item['price']}}</td>
              </tr>
              @php
                $total_price +=$item['price']*$item['qty'];
              @endphp
              @endforeach
            </tbody>
          </table>
          @if(isset($total_price) && $total_price>0)
          <div class="cartFinalInfo text-right">
            <div class="priceHeading">Subtotal: ${{$total_price}}<sup>00</sup></div>
            <!-- <p><em>Taxes and shipping calculated at checkout<em></p> -->
            <div><button type="submit" class="ml-1 mr-1 customBtn01">Pay Now</button></div>
          </div>
          @endif
          @endif
        </div>
      </div>
       </form>
    </div>
  </div>
</section>
<script src="{{ asset('public/frontend/js/jquery.min.js') }}"></script> 
<script>
  $('.plus').on('click',function(e){

    var val = parseInt($(this).prev('input').val());
    var qtry=val+1;
    var productid=$(this).data('item');
    console.log(productid+'--'+qtry);
    updateCartValue(productid,qtry)

    });
    $('.minus').on('click',function(e){

    var val = parseInt($(this).next('input').val());
    if(val > 0){
        var qtry=val-1;
        var productid=$(this).data('item');
        console.log(productid+'--'+qtry);
        updateCartValue(productid,qtry)
    } });


function updateCartValue(product_id,qty)
{
  var csrf_token = $('meta[name=csrf-token]').attr('content');
    $.ajax({
      url: 'update-cart',
      type: 'POST',
      data: {_token: csrf_token, productid:product_id,quantity:qty},
      success: function (data) { 
        location.reload(1);
      }
    });
}

</script>
@endsection('content')

resources/views/pages/contact-us.blade.php
@extends('layouts.frontend-app')

@section('content')
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
    <div class="breadcrumb"><a href="{{route('home')}}">Home</a> <span>></span> Contact Us</div>
    </div>
    </div>
  </div>
</section>
<section class="contentSection">
  <div class="container">
    @if(session('error')) 
            <div class="col-md-12 error alert alert-danger alert-dismissable">
              <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
              <strong>Error : </strong>   {{ session('error') }}
            </div>
          @endif
          @if(session('success')) 
            <div class="col-md-12 error alert alert-success alert-dismissable">
              <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {!! session('success') !!}
            </div>
          @endif
    <div class="row">
      <div class="col-md-12">
        <h1>CONTACT US</h1>

        <div>
          <h2>HAVE A QUESTION?</h2>
          <h3>Speak with Customer Service:</h3>
          <p>1-800-243-5360,2</p>
          <p>customer.service@greenfield.com</p>
          <h3>Speak to A Live Sales Person (M-F 8AM-5PM EST):</h3>
          <p>1-800-243-5360,1</p>
          <h3>Email Marketing:</h3>
          <p>marketing@greenfield.com</p>
          <h3>Technical Questions &amp; Documentation Requests:</h3>
          <p>techsupport@greenfield.com</p>
          <h3>Speak with Accounting:</h3>
          <p>1-800-243-5360,3</p>
          <h3><a class="" href="#" target="_blank">Frequently Asked Questions</a></h3>
          <br>
          <h2>REQUEST A QUOTE / SUPPORT PRICING</h2>
          <form method="post" action="{{route('pages.contact_post')}}">
            @csrf
          
            <label for="companyname">Company Name</label> 
            <input type="text" id="companyname" name="company_name"> 

            <label for="fname">First Name</label> 
            <input type="text" id="fname" name="first_name"> 

            <label for="lname">Last Name</label> 
            <input type="text" id="lname" name="last_name"> 

            <label for="emailaddr">E-mail Address</label> 
            <input type="email" id="emailaddr" name="email_address"> 
            @error('email_address')
              <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
              </span>
              @enderror

            <label for="phonenumber">Phone Number</label> 
            <input type="text" id="phonenumber" name="phone_number"> 
            @error('phone_number')
              <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
              </span>
              @enderror
            <label for="comments">Comments</label> 
            <input type="text" id="comments" name="comments"> 

            <input type="submit" value="SUBMIT" class="submitBtn">
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
@endsection('content')

resources/views/pages/faq.blade.php
@extends('layouts.frontend-app')

@section('content')
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="breadcrumb"><a href="{{route('home')}}">Home</a> <span>></span> FAQ'S</div>
      </div>
    </div>
  </div>
</section>
<section class="contentSection">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>FAQ'S</h1>
        <div>
          <h3>1) HOW CAN I SET UP AN ACCOUNT?</h3>
          <p>If you are an existing customer, our Customer Service team can provide you with your User ID and Password. If you are a new customer, you can apply to set up an account with us by <a class="" href="#" target="_self">clicking here</a>. Our Customer Service team can be reached at 1-800-243-5360 or <a class="" href="mailto:%20customer.service@pharmachemonline.com" target="_blank">customer.service@pharmachemonline.com</a>.</p>
          <h3>2) WHAT FORMS OF PAYMENT DO YOU ACCEPT?</h3>
          <p>We accept credit card payments from Visa, Mastercard, and American Express. In addition, if you have existing payment terms with Greenfield Global you will have the option to "Pay on Account" and will be sent an invoice for your order in accordance with agreed upon terms.</p>
          <h3>3) WHO SHOULD I CONTACT IF I HAVE PROBLEMS WITH THE ONLINE STOREFRONT?</h3>
          <p>Please contact our Customer Service team at 1-800-243-5360,2.</p>
          <h3>4) WHERE CAN I FIND YOUR TERMS AND CONDITIONS?</h3>
          <p>Click <a class="" href="{{route('pages.terms_conditions')}}" rel="" target="_blank">HERE</a> for our terms and conditions.</p>
        </div>
      </div>
    </div>
  </div>
</section>
@endsection('content')

resources/views/pages/my-cart.blade.php
@extends('layouts.frontend-app')

@section('content')
<section class="contentSection">
  <div class="container">
    <div class="row">
      <div class="col-md-12" id="success-message"></div>
      <div class="col-md-12">
        <h2>Shopping Cart</h2>
        <div class="cartBlock">
          @if(isset($cartitems['product']) && count($cartitems['product'])>0)
          <table class="table table-striped cart w-100">
            <thead>
              <tr>
                <th scope="col">Item Name</th>
                <th scope="col">Quantity</th>
                <th scope="col">Price</th>
                <th scope="col" class="text-right">Total Price</th>
              </tr>
            </thead>
            <tbody>
              @php 
                $total_price=0;
              @endphp
              @foreach($cartitems['product'] as $item)
              <tr>
                <td><div class="cartProductInfo d-flex"><div class="cartThumb">
                  <img src="{{asset($item['image'])}}" alt=""></div><p>{{$item['title']}}<br><span class="removeButton">
                    <a href="#" onclick="removeProduct({{$item['id']}})">Remove</a></span></p></div></td>
                <td>
                  <div class="quantity buttons_added">
                    <input type="button" value="-" class="minus" data-item="{{$item['id']}}">
                    <input type="number" step="1" min="1" max="" name="quantity" value="{{$item['qty']}}" title="Qty" class="input-text qty text" size="4" pattern="" inputmode="">
                    <input type="button" value="+" class="plus" data-item="{{$item['id']}}">
                  </div>
                </td>
                <td class="price">${{$item['price']}}</td>
                <td class="price">${{$item['price']*$item['qty']}}</td>
              </tr>
              @php
                $total_price +=$item['price']*$item['qty'];
              @endphp
              @endforeach
             
            </tbody>
          </table>
          @if(isset($total_price) && $total_price>0)
          <div class="cartFinalInfo text-right">

            <div class="priceHeading">Subtotal: ${{$total_price}}<sup>00</sup></div>
            <p><em>Taxes and shipping calculated at checkout<em></p>
            <div>
              <a href="{{route('collections')}}" class="ml-1 mr-1 customBtn01 transparentBtn">Continue Shopping</a> 
              <a href="{{route('checkout')}}" class="ml-1 mr-1 customBtn01"><i class="fa fa-shopping-cart"></i> Checkout</a>
            </div>
          </div>
          @endif
          @else

          <div class="col-md-12">
            <div class="mt-5 mb-5 text-center">
              <div class="emptyCartIcon mt-2 mb-3"><i class="fa fa-shopping-basket" aria-hidden="true"></i></div>
              <h1 class="display-4 mb-3">Your Cart is Empty</h1>
              <p class="lead  mb-4"><strong>Add something to make me happy :)</p>
              <hr>
              <p class="lead">
                <a href="{{route('home')}}" class="ml-1 mr-1 customBtn01 transparentBtn">Back to Homepage</a> 
                <a href="{{route('collections')}}" class="ml-1 mr-1 customBtn01">Continue Shopping</a>
              </p>
            </div>
          </div>
          @endif
        </div>
      </div>

    </div>
  </div>
</section>
<script src="{{ asset('public/frontend/js/jquery.min.js') }}"></script> 
<script>
  $('.plus').on('click',function(e){

    var val = parseInt($(this).prev('input').val());
    var qtry=val+1;
    var productid=$(this).data('item');
    console.log(productid+'--'+qtry);
    updateCartValue(productid,qtry)

    });
    $('.minus').on('click',function(e){

    var val = parseInt($(this).next('input').val());
    if(val > 0){
        var qtry=val-1;
        var productid=$(this).data('item');
        console.log(productid+'--'+qtry);
        updateCartValue(productid,qtry)
    } });


function updateCartValue(product_id,qty)
{
  var csrf_token = $('meta[name=csrf-token]').attr('content');
    $.ajax({
      url: 'update-cart',
      type: 'POST',
      data: {_token: csrf_token, productid:product_id,quantity:qty},
      success: function (data) { 
        location.reload(1);
      }
    });
}

</script>
@endsection('content')

resources/views/pages/page-detail-bk29032022.blade.php
@extends('layouts.frontend-app')

@section('content')
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="breadcrumb"><a href="{{route('home')}}">Home</a> <span>></span> 
          <span>></span> {{(isset($pagedetail->title))?$pagedetail->title:''}}</div>
      </div>
    </div>
  </div>
</section>
<section class="contentSection">
  <div class="container">
    <div class="row">
     	{!! $pagedetail->content!!}
    </div>
  </div>
</section>
<style type="text/css">
  .flex_container_pd {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
}
.rte {
    margin-bottom: 15px;
}
.flex_container_pd > .flex_item_left_1_pd {
    width: 33%;
}
.flex_container_pd > .flex_item_right_2_pd {
    width: 67%;
    padding-left: 2%;
}
.rte table {
    table-layout: fixed;
}
table {
    border-collapse: collapse;
    border-spacing: 0;
    min-width: 50%;
}
th, td {
    text-align: left;
    padding: 15px;
    border: 1px solid #dedede;
}
.flex_container_pd_supporting {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
}
.flex_container_pd_supporting > .flex_item_pd_supporting {
    text-align: center;
    width: 20%;
}

a {
    color: #9c756f;
    text-decoration: none;
    background: transparent;
}
img.auto, .grid-item img, .grid-item iframe {
    max-width: 100%;
}
</style>
@endsection('content')

resources/views/pages/page-detail.blade.php
@extends('layouts.frontend-app')

@section('content')
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="breadcrumb"><a href="{{route('home')}}">Home</a> <span>></span> 
          <span>></span> {{(isset($pagedetail->title))?$pagedetail->title:''}}</div>
      </div>
    </div>
  </div>
</section>
<section class="contentSection">
  <div class="productDocumentPages">
	  <div class="container">
		<div class="row">
			{!! $pagedetail->content!!}
		</div>
	  </div>
  </div>
</section>

@endsection('content')

resources/views/pages/product-documentation.blade.php
@extends('layouts.frontend-app')

@section('content')
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
    <div class="breadcrumb"><a href="#">Home</a> <span>></span> PRODUCT DOCUMENTATION</div>
    </div>
    </div>
  </div>
</section>
<section class="contentSection">
   <div class="container">
      <div class="row">
         <div class="col-md-12">
           <h1>PRODUCT DOCUMENTATION</h1>
         </div>
         <h2>PRODUCT LIST</h2>

         <p class="col-md-12">Select any product to access more information including specifications, safety data sheets and more.</p>
         @foreach($results as $key=>$result)
         <div class="product-list-{{strtolower($key)}}">
            <h3>{{$key}}</h3>
            <div class="product-list-flex-container col-md-12">
               @if(isset($result) && count($result)>0)
                  @foreach($result as $page)
                     <h4 class="col-md-6"><a href="{{route('pages_details',$page->slug)}}"  rel="nofollow" target="_self">{{$page->title}}</a></h4>
                  @endforeach
               @endif
            </div>
         </div>
         @endforeach
      </div>
   </div>
</section>
@endsection('content')

resources/views/pages/terms-conditions.blade.php
@extends('layouts.frontend-app')

@section('content')
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
    <div class="breadcrumb"><a href="{{route('home')}}">Home</a> <span>></span> Terms and Conditions</div>
    </div>
    </div>
  </div>
</section>
<section class="contentSection">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>Terms and Conditions</h1>

        <div>
          <object data="{{ asset('public/frontend/pdf/Terms-and-Conditions-07Dec2020.pdf') }}" type="application/pdf" width="1100" height="1200">
            <a href="{{ asset('public/frontend/pdf/Terms-and-Conditions-07Dec2020.pdf') }}">terms and conditions.pdf</a>
          </object>
        </div>
      </div>
    </div>
  </div>
</section>
@endsection('content')